### ISSUE TITLE
[ITensors] [BUG] Looping through symmetric tensors

### ISSUE THREAD

**Issue by ArtemStrashko** [ITensor/ITensors.jl#1162]
**Description of bug**

It looks like direct application of [a recipe of writing performant code (looping through tensor elements)](https://itensor.github.io/ITensors.jl/stable/AdvancedUsageGuide.html#ITensor-type-design-and-writing-performant-code) does not work for [symmetric tensors](https://itensor.github.io/ITensors.jl/stable/QNTricks.html).

**Minimal code demonstrating the bug or unexpected behavior**

```julia
using ITensors
i = Index([QN(0) => 2, QN(1) => 3], "i")
j = Index([QN(0) => 2, QN(1) => 3], "j")
A = randomITensor(i, dag(j))
function myscale!(A::Array, x::Number)
    for n in 1:length(A)
        A[n] = x * A[n]
    end
end
myscale!(A::ITensor, x::Number) = myscale!(array(A), x)
myscale!(A, 2)
```
For dense tensors this works well, while for block-sparse tensors, `myscale!(A, 2)`, does not change tensor `A`.
</p></details>

**Expected output or behavior**

In-place modification of an original tensor similar to how it works a dense tensor.

**Actual output or behavior**

`A` is not modified.

**Version information**

 - Output from `versioninfo()`:
```julia
julia> versioninfo()
Julia Version 1.9.2
Commit e4ee485e909 (2023-07-05 09:39 UTC)
Platform Info:
  OS: macOS (arm64-apple-darwin22.4.0)
  CPU: 10 × Apple M1 Max
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-14.0.6 (ORCJIT, apple-m1)
  Threads: 1 on 8 virtual cores
Environment:
  JULIA_PKG_USE_CLI_GIT = true

```
 - Output from `using Pkg; Pkg.status("ITensors")`:
```julia
julia> using Pkg; Pkg.status("ITensors")
ITensors v0.3.35
```

**Comment by mtfishman** [comment]
Thanks for the report. The issue is that `array(...)` on a BlockSparse Tensor makes an `Array` since Julia doesn't have an equivalent block sparse array type for us to convert to, and therefore doesn't make a view of the underlying data. You could directly extract the underlying data with `ITensors.data(A)`, which is similar to your solution but a bit more direct. Also you could use broadcasting `A .*= 2`, which should be fast since internally it only acts on `ITensors.data(A)`.

**Comment by mtfishman** [comment]
Basically because of the behavior of `array` this isn't expected to work, so I'll close.
