### ISSUE TITLE
[ITensors] [BUG] Incompatible NDTensors version between ITensors and ITensorGPU

### ISSUE THREAD

**Issue by EmilioRui** [ITensor/ITensors.jl#1163]
**Description of bug**

ITensors and ITensorGPU rely on different NDTensors version, and using them both is currently not possible

**Minimal code demonstrating the bug or unexpected behavior**

<details><summary>Minimal runnable code</summary><p>

```julia
using Pkg
Pkg.add("ITensors")
Pkg.add("ITensorGPU")
```
</p></details>

**Comment by mtfishman** [comment]
Do you have NDTensors pinned to a certain version? If so, you should free it and allow Julia to downgrade it to the version compatible with ITensorGPU.

**Comment by EmilioRui** [comment]
Thank you for the quick response.
It is free to downgrade to ITensorGPU version (0.1.51)
ITensors can no more be compiled.

Vanilla Julia:

``` using Pkg
Pkg.add("ITensors")
Pkg.add("ITensorGPU")

using ITensors
```
I get an import error associated to the NDTensors.

I get:
```
ERROR: LoadError: UndefVarError: `get_parameters` not defined


/julia/dev/ITensors/src/imports.jl:132

```

That is this line 
``` using ITensors.NDTensors.SetParameters: get_parameters, set_unspecified_parameters
```

**Comment by EmilioRui** [comment]
I know it is in dev as I was updating a small bit, but I have done it also in a fresh Install

**Comment by mtfishman** [comment]
I see, ITensorGPU is only compatible with ITensors v0.3.37 and below. I had fixed that explicitly in ITensorGPU but didn't register a new version. I'm registering it now. For the time being, you could do `add ITensors@0.3.37`, and the new version of ITensorGPU (v0.1.5) will be registered soon which fixes the version of ITensors automatically.

We are moving towards using a package extension instead of ITensorGPU. Basically you can use it by just removing `ITensorGPU`, and then when you upgrade your packages, when you load both the CUDA and ITensors packages, it automatically loads the `NDTensorCUDA` extension. It should have most of the functionality of `ITensorGPU` at this point, let us know if you tried it out and come across any issues.

**Comment by mtfishman** [comment]
Should be fixed by https://github.com/ITensor/ITensors.jl/commit/73bc07eded9bd5f88da1a1562986ac5fb6e42a10. @EmilioRui please let us know if this is still an issue.

**Comment by EmilioRui** [comment]
It does work when installing ITensorGPU with the new version.

Just to let you know at the moment when you add ITensorGPU the default version installed is still the 0.1.5.
(I honestly do not know if it is just a matter of time for it to update or if you need to do something, I am still in the julia learning phase)

By the way thank you so much for the quick fix!
