### ISSUE TITLE
Mistake in Spin 1/2 operator Sy

### ISSUE THREAD

**Issue by jtschneider** [ITensor/ITensors.jl#152]
https://github.com/ITensor/ITensors.jl/blob/72b0bd9b2c9c2f37d311a4e3958f20d08ad7c069/src/physics/site_types/spinhalf.jl#L39-L45

There is a non-canonical definition of the Pauli matrix `\sigma_y`; it has a sign error with respect to the canonical definition [1,2]:

<img width="215" alt="image" src="https://user-images.githubusercontent.com/9451057/70255514-3e366f00-1787-11ea-8932-de90bc88f928.png">

Obviously, this is only noticeable in operators which are odd in `\sigma^y` and thus this might be a mild bug. However, I wish to argue that we should fix the sign in order to not throw the commutation relations 

<img width="128" alt="image" src="https://user-images.githubusercontent.com/9451057/70255041-67a2cb00-1786-11ea-8bd1-88a632c17f9c.png">

over board as they indeed **define** the Pauli matrices in a basis-independent way. NB: Anti-commutation relations are still valid under `\sigma^y -> -\sigma^y` (even in `\sigma^y`).
Currently, the commutation relations **do not hold**.

Moreover, `\sigma^+` and `\sigma^-` would have to change role as

<img width="161" alt="image" src="https://user-images.githubusercontent.com/9451057/70255167-9e78e100-1786-11ea-8063-13580e17fe43.png">

https://github.com/ITensor/ITensors.jl/blob/72b0bd9b2c9c2f37d311a4e3958f20d08ad7c069/src/physics/site_types/spinhalf.jl#L32-L35

Cheers,
Jan

[1] W. Pauli, „Zur Quantenmechanik des magnetischen Elektrons", Zeitschrift für Physik, Bd. 43, 1927, S. 601, DOI: [10.1007/BF01397326](https://link.springer.com/article/10.1007%2FBF01397326)
[2] [Pauli matrices, Wikipedia (en)](https://en.wikipedia.org/wiki/Pauli_matrices), visited: 05/12/2019 at 17:00UTC+1

**Comment by jtschneider** [comment]
I propose a fix with Pull Request https://github.com/ITensor/ITensors.jl/pull/153 .

**Comment by emstoudenmire** [comment]
Thanks Jan, however I believe you are reading the matrices in a transposed way relative to how the code operates. With the ITensor system, the line of code:
`Op[Dn, UpP] = -0.5*im`
has exactly the same effect as the line of code
`Op[UpP, Dn] = -0.5*im`
That is, the order of the indices does not matter. But I can see that it's confusing how I wrote them in the reverse order from the usual row,column ordering. (I think I was thinking in a left-to-right "down maps to up" fashion when I wrote that code.)

So actually the existing code does agree with the canonical definition of the Pauli y matrix.

I think a good correction, though, would be to reverse the order of the Up,Dn,UpP,DnP arguments throughout that whole code so that it is less confusing to read though.

**Comment by jtschneider** [comment]
Hi Miles,

Consider the following test:
```julia
julia> using ITensors

julia> sites = ITensors.siteinds("S=1/2", 1)
1-element Array{Index,1}:
 (2|id=217|S=1/2,Site,n=1)

julia> Sx = op(sites[1], "Sx"); Sy = op(sites[1], "Sy"); Sz = op(sites[1], "Sz");

julia> @show Sx
Sx = ITensor ord=2 (2|id=90|S=1/2,Site,n=1) (2|id=90|S=1/2,Site,n=1)'
Dense{Float64,Array{Float64,1}}
2×2 Tensor{Float64,2,Dense{Float64,Array{Float64,1}},IndexSet{2}}:
 0.0  0.5
 0.5  0.0
ITensor ord=2 (2|id=90|S=1/2,Site,n=1) (2|id=90|S=1/2,Site,n=1)'
Dense{Float64,Array{Float64,1}}

julia> @show Sy
Sy = ITensor ord=2 (2|id=90|S=1/2,Site,n=1) (2|id=90|S=1/2,Site,n=1)'
Dense{Complex{Float64},Array{Complex{Float64},1}}
2×2 Tensor{Complex{Float64},2,Dense{Complex{Float64},Array{Complex{Float64},1}},IndexSet{2}}:
  0.0+0.0im  0.0+0.5im
 -0.0-0.5im  0.0+0.0im
ITensor ord=2 (2|id=90|S=1/2,Site,n=1) (2|id=90|S=1/2,Site,n=1)'
Dense{Complex{Float64},Array{Complex{Float64},1}}

julia> @show Sz
Sz = ITensor ord=2 (2|id=90|S=1/2,Site,n=1) (2|id=90|S=1/2,Site,n=1)'
Dense{Float64,Array{Float64,1}}
2×2 Tensor{Float64,2,Dense{Float64,Array{Float64,1}},IndexSet{2}}:
 0.5   0.0
 0.0  -0.5
ITensor ord=2 (2|id=90|S=1/2,Site,n=1) (2|id=90|S=1/2,Site,n=1)'
Dense{Float64,Array{Float64,1}}

julia> @show Sx*Sy' - Sy*Sx'
Sx * Sy' - Sy * Sx' = ITensor ord=2 (2|id=90|S=1/2,Site,n=1) (2|id=90|S=1/2,Site,n=1)''
Dense{Complex{Float64},Array{Complex{Float64},1}}
2×2 Tensor{Complex{Float64},2,Dense{Complex{Float64},Array{Complex{Float64},1}},IndexSet{2}}:
 0.0-0.5im  0.0+0.0im
 0.0+0.0im  0.0+0.5im
ITensor ord=2 (2|id=90|S=1/2,Site,n=1) (2|id=90|S=1/2,Site,n=1)''
Dense{Complex{Float64},Array{Complex{Float64},1}}

```

The line `julia> @show Sy` offers a view of the implemented `Sy` operator and it is indeed printed as the non-canonical version. Additionally, `julia> @show Sx*Sy' - Sy*Sx'` yields a view on the result of the commutator `Sx Sy - Sy Sx` which is indeed `-Sz`.

**Comment by emstoudenmire** [comment]
Hi Jan, yes this printout does show it in reverse order from the canonical version, but in ITensor the definition of a tensor is independent of the index ordering. So here the reason you see the reverse order of the elements is because the indices are ordered as column, row rather than row, column (in the sense of mapping onto the standard row and column indices of the Pauli matrices).

In ITensor, our convention is that the unprimed index is the “bra” index i.e. the column index, whereas the primed index is the “ket” index so the row index. So it’s confusing here because I ordered the indices backwards from the usual row, column ordering which is standard for matrices, however the definition of an ITensor is invariant to this ordering (although the printout is not, which is why we also print the indices). 

Best regards,
Miles

**Comment by emstoudenmire** [comment]
The issue you filed is very appreciated by the way. Based on your issue I will go through and change the ordering of the operator indices in the S=1/2 and similar parts of the code so that the printouts follow the standard row, column ordering.

**Comment by jtschneider** [comment]
Oh, I see, so in fact the printout would be transposed as well as `matrix(op(sites[1],"Sy"))`...

I'm sorry, I completely forgot about the unprimed <-> bra, primed <-> ket convention.
