### ISSUE TITLE
`norm(v::ITensor)` became very slow (performance regression)

### ISSUE THREAD

**Issue by orialb** [ITensor/ITensors.jl#184]
Hi,
I noticed that my TDVP code became extremely slow with latest master (edit: also DMRG is extremely slow, see comment below). After some profiling I think the problem is related to `norm(v::ITensor)` becoming extremely slow.
I did some git bisecting and I believe this regression was introduced in https://github.com/ITensor/ITensors.jl/pull/171. 

Using the following code to benchmark:
```julia
using ITensors, BenchmarkTools
i = Index(1000)
v = randomITensor(i)
@btime norm(v)
```
I get on master (https://github.com/ITensor/ITensors.jl/commit/b6279695d3824f5554cf9b2f349c970a460bba90): 
```julia
julia> @btime norm(v)
  2.501 ms (18025 allocations: 344.16 KiB)
```
While on https://github.com/ITensor/ITensors.jl/commit/6ae3e7b89fd18c4a1c3046fbd42717df908ac265 I get:
```julia
julia> @btime norm(v)
  3.976 μs (3 allocations: 64 bytes)
```

So it seems that `norm` became 3 orders of magnitude slower and is allocating a lot. 
I'll try to keep digging into it, but if you have some idea of what can be the reason let me know.

**Comment by orialb** [comment]
Not sure if that is the problem, but it also seems that `getindex` for `DenseTensor` got slower (and in the profiling graph I saw that the majority of time of `norm` is spent in `getindex`).

```julia
using ITensors, BenchmarkTools
i = Index(1000)
t = tensor(randomITensor(i))
@btime t[1]
```
I get `1.189 μs (7 allocations: 112 bytes)` on master, and `24.920 ns (1 allocation: 16 bytes)` on 6ae3e7b .

**Comment by mtfishman** [comment]
Thanks a lot for catching and fixing this. There are a lot of changes going on in the `Tensors` module as we work on the BlockSparseTensor functionality, so I am not surprised that issues like this are showing up. I will investigate the regression in `getindex`, I think it is likely that there are a lot of performance improvements to make for basic `Tensor` functionality.

This definitely points to a need to have systematic benchmarks that can be run for each pull request (and note that it may be good to be careful about following along with master at this time).

**Comment by orialb** [comment]
> This definitely points to a need to have systematic benchmarks that can be run for each pull request

Maybe there can be a test running 2-3 sweeps of the 1d Heisenberg model and checking that the the time for each sweep is smaller than some threshold? This is of course not extensive but can at least prevent some extreme regression. I could make a PR if you think it is a good idea.

> and note that it may be good to be careful about following along with master at this time.

Maybe it's worth tagging a version (0.0.1 or something like this) and pointing users to it in the installation instructions in the README? (or even registering it so it can be installed form the package manager).

**Comment by mtfishman** [comment]
I am hesitant to put that in the tests right now since the tests are already taking quite a long time (Miles and I were discussing ways to decrease the testing time, I find that it slows down development time since I run the test suite pretty often while I work on features). Perhaps we can set it up as a separate `benchmark` directory (not in the tests), and we can make sure to run it periodically and keep track of the times. Ultimately we want a comprehensive benchmark system like BaseBenchmarks.jl (but it is not a high priority right now as we are working on completing the QN functionality).

We could start tagging minor versions, though things are getting developed quite quickly so it is hard to say if the library is stable enough for that. We had decided to wait to register the package once the QN functionality was completed (which should be fairly soon, since we only have QN ITensor decompositions and a QN version of AutoMPO left), as a warning to people that the library is still pre-release and breaking changes are expected.

**Comment by orialb** [comment]
Understood, looking forward for the QN features :)
