### ISSUE TITLE
Move siteinds function

### ISSUE THREAD

**Issue by emstoudenmire** [ITensor/ITensors.jl#261]
Right now, the siteinds function is defined in the physics/tag_types.jl file. But the conventions it uses, of "Site" tags on site indices, are common throughout general applications of MPS. So it would make sense for this function and related functions to be defined in mps.jl or similar.

**Comment by mtfishman** [comment]
Good point. Also, in C++ we moved to using `uniqueind` instead of the "Site" tag to find site indices, for a bit more generality (to be agnostic to tag conventions, for example the site index of a boundary MPS of a PEPS may not naturally have a "Site" tag). I go back and forth about that design decision, but I think it has generally worked well. I don't think it has much of a downside, since it still works even if it is a product state MPS with no link indices.

**Comment by emstoudenmire** [comment]
Something we should think about, but I'm going to close this for now because it's probably more relevant if and when we split off the physics features into their own package, say. For now there's a good argument to be made for keeping the siteinds functions together in the file physics/sitetype.jl just to make it easy to inspect them all together.
