### ISSUE TITLE
Operator tracker for DMRG

### ISSUE THREAD

**Issue by kshyatt** [ITensor/ITensors.jl#32]
In the C++ code, you can include operators you want DMRG to measure as it sweeps back and forth, to see how the entropy/magnetization/whatever are doing. It would be nice to have this feature in the Julia code too.

**Comment by emstoudenmire** [comment]
Yes, we do need to add this back

Here’s the design we currently have in C++ and how it would work in Julia approximately:
* you can optionally pass some object to DMRG that is the “observer” or “tracker” object (the name is not so important!)
* this object needs to support two methods: `measure` and `checkDone`. We can provide a default implementation of each of these in some way (is there a way in Julia to see if a method is defined, and call it, otherwise call a fallback method? Inheriting from some abstract type can let you do this by defining the method for the abstract type but then it means you have to inherit - not the worst thing in this use case)

As an alternative it might possible to just pass the measure and checkDone *functions* themselves in Julia, and if you want them to have access to some data use functional programming tricks like currying with a lambda or similar to wrap the data inside them (we could provide simple examples).

**Comment by kshyatt** [comment]
This seems like it might be a good project for the Hackathon tomorrow...

**Comment by emstoudenmire** [comment]
Yes! Great idea

**Comment by orialb** [comment]
If no one is working on this I can have a go at this. In my own MPS code I pass an observer object and I have a tendency to prefer this way.  
I didn't fully understand from the design suggestion whether you want to support the two alternatives (object vs. passing functions directly),  or prefer choosing one or the other.

**Comment by emstoudenmire** [comment]
Thanks Ori. I think that would be great. Let's prefer choosing just one design. My comment about passing functions was too vague, and more to say that maybe Julia gives us a chance to revisit the design we have in C++.

But upon further thought, the design we have in C++ seems good to me. It's just that subtyping classes in C++ is a pain and very verbose, whereas in Julia it's quite straightforward. So the design gets that much better as we port it to Julia.

Looking forward to seeing what you develop -

**Comment by emstoudenmire** [comment]
Addressed in pull requeest #89 - thanks to Ori Alberton @orialb for contributing this.
