### ISSUE TITLE
In and Out conflict with Jupyter notebook variables

### ISSUE THREAD

**Issue by mtfishman** [ITensor/ITensors.jl#356]
Giacomo pointed out that if you are using a Jupyter notebook, it already defines some global variables `In` and `Out` which are dictionaries storing a history of the command inputs and outputs. This conflicts with the arrow directions `ITensors.In` and `ITensors.Out`, and gives a warning about that.

Not sure if this is something we should worry about, we could consider not exporting `In` and `Out` (since they aren't used much explicitly), and if someone is using them a lot they could explicitly do `import ITensors: In, Out`.

**Comment by emstoudenmire** [comment]
Yes, I agree about not exporting them. Actually, Mason Protter had brought this issue up before (see issue #9) and so we stopped exporting In and Out in this commit in response: 79d3d9. But since then they got exported again, I think during the creation of the file exports.jl.

So I'm all for taking them out of exports.jl and just requiring people to explicitly import them in the way you said. It's a good solution.

**Comment by mtfishman** [comment]
Ah I had totally forgotten about that issue, thanks for the reminder. Indeed, let's remove them as exports.
