### ISSUE TITLE
Use a Dict to store op definitions

### ISSUE THREAD

**Issue by mtfishman** [ITensor/ITensors.jl#375]
We could consider using a `Dict` of functions to store op definitions. The two advantages would be to avoid long lists of `if [...] elseif [...]` statements, and to make the `op` function extensible since a user could define their own op and add it to the dictionary, instead of modifying the `op` function/making a PR.

Here would be the design:
```julia
function spinhalf_op_Splus(s::Index)
  Up = s(1)
  UpP = s'(1)
  Dn = s(2)
  DnP = s'(2)
  Op = emptyITensor(s',dag(s))
  Op[UpP, Dn] = 1.
  return Op
end

function spinhalf_op_Sx(s::Index)
  Up = s(1)
  UpP = s'(1)
  Dn = s(2)
  DnP = s'(2)
  Op = emptyITensor(s',dag(s))
  Op[UpP, Dn] = 0.5
  Op[DnP, Up] = 0.5
  return Op
end

spinhalf_ops = Dict()
spinhalf_ops["Splus"] = spinhalf_op_Splus
spinhalf_ops["Sx"] = spinhalf_op_Sx

function op(::SpinHalfSite,
            s::Index,
            opname::AbstractString)
   return spinhalf_ops[opname](s)
end
```
We can of course make a helper function to avoid code duplication when defining the IndexVals and emptyITensor for each operator.

Then, someone can just define their own function:
```julia
function spinhalf_op_myop(s::Index)
  Up = s(1)
  UpP = s'(1)
  Dn = s(2)
  DnP = s'(2)
  Op = emptyITensor(s',dag(s))
  Op[UpP, Dn] = 12
  Op[UpP, DnP] = 7
  Op[DnP, Up] = 0.2
  return Op
end
# Maybe don't export at first
ITensors.spinhalf_ops["myop"] = spinhalf_op_myop
# Then this should work:
s = Index(2, "S=1/2")
op(s, "myop")
```

**Comment by emstoudenmire** [comment]
This is definitely something we should think about, because being able to extend the op function from a user code would be a powerful feature for things like AutoMPO. I like the proposal above, with one twist which is that we can additionally define `getindex` and `setindex!` overloads which take Index=>String pairs (or just Strings if the index ordering is assumed). Then the code inside of each function could be like:

```
function spinhalf_op_myop(s::Index)
  Op = ITensor(s',dag(s))
  Op[s'=>"Up", s=>"Dn"] = 12
  Op[s'=>"Dn", s=>"Up"] = 0.2
  return Op
end
```

One other thing to consider is whether this feature would be better or worse if we took the extra step of always guaranteeing that `op` returns order-2 ITensors, with the Index structure (s',dag(s)). Then we could hypothetically make the "myop" functions even simpler e.g. by having the machinery pass an already constructed ITensor to them to be modified. But maybe this is overkill because the kind of code above is easy enough to learn and gives users practice with basic ITensor features. Also it shows them how this machinery is just using regular ITensor features and isn't "magical" code.

**Comment by mtfishman** [comment]
I like that suggestion. I think with the `setindex!` syntax you are proposing it is quite simple to implement, so it doesn't seem necessary to make it any simpler.

Also, there may be cases where someone wants to make larger operators (like two-site gates, for example a CNOT in the context of quantum computing). Those can of course be made out of on-site operators, but are clearly more natural to define directly. So it would be nice to keep the machinery more general.

**Comment by emstoudenmire** [comment]
Closing this issue, because it’s been superseded by the SiteType design that uses overloading instead of a global Dict.
