### ISSUE TITLE
num_cpus in parallelization?

### ISSUE THREAD

**Issue by vipasu** [ITensor/ITensors.jl#378]
Hi,

I have a pretty naive question. I notice that when I run the dmrg function on my laptop it makes use of multiple cores automatically (neat!). I'm now interested in running the same code on a server that has nodes/cores structure. Obviously it would be great to utilize all of the cores on a given node. I couldn't find where in the code this type of parallelization (e.g. num_cpus to use) is specified, so I was wondering if you might be able to point me to where this gets configured.

For reference, in my cluster job, I specify 1 node with 20 cpus, but it doesn't seem to run much faster than a 6 core desktop. It's possible the communication overhead eats into the speedup, but I would like to make sure I'm not missing easy parameters to tweak.

Thanks!

**Comment by mtfishman** [comment]
There are two possible sources of parallelization available in ITensors.jl, both external to the package right now. These are:
 - BLAS/LAPACK multithreading (through whatever flavor you are using, i.e. OpenBLAS or MKL).
 - The Strided.jl package, which implements a multithreaded array permutation.

The BLAS/LAPACK multithreading can be controlled in the usual way with environment variables, or within Julia. So for example, to control from Julia, you would do:
```julia
julia> using LinearAlgebra

julia> BLAS.vendor()  # Check which BLAS you are using
:mkl

julia> BLAS.set_num_threads(4)

julia> ccall((:MKL_GET_MAX_THREADS, Base.libblas_name), Cint, ())
4

julia> BLAS.set_num_threads(2)

julia> ccall((:MKL_GET_MAX_THREADS, Base.libblas_name), Cint, ())
2
```
(if you are using OpenBLAS, I think you would get the number of threads with `ccall((:openblas_get_num_threads, Base.libblas_name), Cint, ())` but I haven't checked).

Alternatively, you can use environment variables, so at your command line prompt you would use:
```
~ export MKL_NUM_THREADS=4
```
if you are using MKL or
```
~ export OPENBLAS_NUM_THREADS=4
```
if you are using OpenBLAS. We would highly recommend using MKL (you can easily add MKL support to an existing Julia build with https://github.com/JuliaComputing/MKL.jl), especially if you are using an Intel chip. In general, we have not found MKL/OpenBLAS multithreading to help much in the context of DMRG, and I would be very surprised if it scaled to 20 cores. How well it scales would depend highly on the problem you are studying, and would require your calculation to be vastly dominated by matrix multiplications (which is not always the case, especially if you are using QN conservation).

Then, a separate level of mutlithreading could be turned on, which is native Julia multithreading. Right now in ITensors.jl, this would only control array permutation functions we use from [Strided.jl](https://github.com/Jutho/Strided.jl). You would set it with the environment variable `JULIA_NUM_THREADS`, for example:
```julia
julia> Threads.nthreads() # By default it is probably off
1
```
Then if you set `export JULIA_NUM_THREADS=4` at your command line, you would see the next time you start up Julia:
```julia
julia> Threads.nthreads()
4
```
Currently, we have not found that using that kind of multithreading has helped either, and I have seen it cause slowdowns, possibly because it is competing with BLAS multithreading (Jutho, the author of the package, is aware of those problems and it will hopefully improve in the future).

On top of that, we hope to incorporate our own multithreading with Julia's native multithreading capabilities, for example to parallelize over block sparse contractions. We have that implemented in the C++ version of ITensor, and it works very well (for certain problems, it did in fact scale up to 20 cores).

**Comment by vipasu** [comment]
Great, thanks for the thorough response!
