### ISSUE TITLE
preserve indices in `orthogonalize!`  ?

### ISSUE THREAD

**Issue by orialb** [ITensor/ITensors.jl#386]
I think the fact that the following code:
```julia
sites = siteinds("S=1/2",10)
psi = productMPS(sites, fill("↑",10))
orthogonalize!(psi,length(psi))
orthogonalize!(psi, 1)
```
has the side effect of replacing all the bond indices of `psi`, even when no truncation is performed, can be surprising. 

For example this could lead to some bugs when one is trying to perform some measurements  on an MPS and there is also some `ProjMPO` hanging around (e.g. in DMRG or TDVP)- if one uses `orthogonalize!` one has to also rebuild the `ProjMPO`. 

Although one could work around this in this example, I think it would be nice in general  and make it a bit easier to reason about the code, to have `orthogonalize!` not changing the indices (maybe this behavior could be controlled with a keyword if it affects performance).

But maybe I'm missing something and this would be an expensive/complicated thing to do in the case of QN indices, or in general because the ordering of the underlying storage might change?

**Comment by emstoudenmire** [comment]
Hi Ori, thanks for asking about this. I see what you mean about it not being so obvious why the indices might change when no truncation is being performed so that the indices remain the same size.

However, after thinking about it some more I remain strongly convinced that it’s the right behavior for the indices to change, even if they aren’t truncated. Here are some different, but related thoughts about why:

- after a gauge transformation, all of the parameters of the tensors in the MPS have (typically) changed, so why not the bond indices too?
- more to the point, after the call to `orthogonalize!(psi,length(psi))` each bond index describes an orthonormal basis on the subsystem to the left of that bond, whereas after the call to `orthogonalize!(psi,1)` each bond index now describes an orthonormal basis on the subsystem to the right of that bond. So the basis they describe is very different after those different calls to `orthogonalize!`. Therefore why should they be the same indices?
- if one has previously set up a `ProjMPO` with the MPS, then changed its gauge in an arbitrary way, then typically the `ProjMPO` is no longer valid, at least not in a way that is useful with the new MPS tensors. Even if the bond dimensions remained the same so that the new tensors could technically be contracted with the (now invalidated) `ProjMPO` environment (left/right edge) tensors, doing so would typically lead to incorrect results. So here the ITensor approach to things is actually protecting the user from making a serious mistake.
- in the case of QN conservation, we follow a convention that the Index arrows flow outward from the site that is the orthogonality center of the gauge. So calls to `orthogonalize!` generally change the arrow directions, and that’s another reason the indices need to change (or at a minimum their arrow directions need to change).

If it helps, you can think of a two-site MPS, which is really just a matrix factorized into a product A*B. Then the various gauges are related to the SVD, as you know, A*B = U*S*V. So the question of whether the bond indices should be the same when in left versus right canonical form is like asking whether the index connecting U to S is really the same as the one connecting S to V. They are not, because one labels the left singular vectors while the other labels the right singular vectors.

Hope that helps! We could discuss more if there’s a specific use case I’m not thinking of where having the indices stay the same makes the code both easier to use and correct to use.

**Comment by orialb** [comment]
Thanks a lot for the detailed reply Miles, I think it makes sense.

I guess my main problem was actually the fact that I didn't take into account that the `ProjMPO` and `MPS` objects are coupled and I'm passing only the MPS to the measurement callback, so one has to take care there. 
The reason why it produced a confusing error is that after the index mismatch `P(wf)` (with `P::ProjMPO` and `wf` the two-site wavefunction) will not throw an error but will return an `ITensor` with the wrong number of indices.  
Since one would expect that `P(wf)` will produce an ITensor with the same shape as `wf`, maybe `product(P::ProdMPO,wf::ITensor)` should throw an exception in case of index mismatch (or maybe just when debug mode is enabled to not hurt performance)? If you think this makes sense I can open a new issue to discuss this.   

p.s. Congrats on the package registration !

**Comment by emstoudenmire** [comment]
Thanks for explaining the situation you were observing; it makes a lot of sense you'd wonder about this issue of indices and the ProjMPO behavior.

Yes, I think a better error message is certainly warranted there, as you're right that ProjMPO can know how many indices the result should have. (There are many such places throughout the library where error messages could be better; it's always an ongoing battle with a library, especially a new one.)

If you filed an issue about that, I think we can treat this as a kind of bug for sure (better error message needed bug). Thanks!
