### ISSUE TITLE
Consider refactoring into a few smaller packages

### ISSUE THREAD

**Issue by MasonProtter** [ITensor/ITensors.jl#39]
So ITensors.jl is turning into quite the large dependency and will only get bigger. Certain users may only be interested in the tensor parts whereas others will be interested in the MPS parts. Perhaps, the ITensor type and all the low level stuff can live in one package and the MPS / DMRG algorithms that live on top should be in a separate package that depends on the package that exports `ITensor`. 

Just a thought, might cause some developer inconveniences while things are moving fast and breaking, but it seems like it might be a good long term thing.

One immediate benefit is that it would really cut down on CI test times...

**Comment by mtfishman** [comment]
Yes, we were discussing this and would like to split off (at least some of the) storage code into another package, as well as split off the more physics-related things like SiteSet and AutoMPO. We were going back and forth about if the MPS/MPO code should be a separate package, I think this is still an open question.

For now for simplicity, since the package is under heavy development, we will keep it like this, but we will try to make the parts modular so it is easy to do in the future when it is ready.
