### ISSUE TITLE
Julia version 1.3.1 incompatible with latest version of ITensors?

### ISSUE THREAD

**Issue by sujay-kazi** [ITensor/ITensors.jl#397]
Is the latest version of ITensors not compatible with Julia 1.3.1? Previous versions of ITensors have worked with this version of Julia, but just now I tried to add the latest version and got the following error:

![ITensors_latest_version_incompatible_with_Julia_version_1 3 1](https://user-images.githubusercontent.com/45156122/82977989-53eb5b00-9f98-11ea-9a2e-d64a4ee2bc61.PNG)

If this is not the case, am I doing something wrong? If this is the case, is there a reason for the change, and can it be stated in an easy-to-find place? Because I don't see it anywhere on the documentation (https://itensor.github.io/ITensors.jl/stable/) or on the README.md file (https://github.com/ITensor/ITensors.jl), where I assumed something like this would be mentioned.

**Comment by mtfishman** [comment]
Yes, right now ITensors.jl relies on a feature only available in Julia v1.4, so we set that as a requirement. We are using a new version of `filter` that works for Tuples that was introduced in Julia v1.4.

We can make a note of it in the installation instructions. I'm not sure what the standard practice is for Julia packages for supporting older minor versions of Julia. It looks like the [Compat.jl](https://github.com/JuliaLang/Compat.jl) package may be able to help us make ITensors.jl compatible with older versions of Julia. I'll make an issue to look into that, since I guess that would be a good way to let us use the newest Julia features but not force people to always use the latest Julia version.

**Comment by mtfishman** [comment]
I added a note [here](https://github.com/ITensor/ITensors.jl/blob/master/docs/src/index.md) and raised an issue (#398) about using Compat.jl to support older versions, so I'll closes this.

**Comment by mtfishman** [comment]
Note that we now support Julia 1.3 and later (from #468), but not earlier.
