### ISSUE TITLE
Set a good default truncation in `contract(::MPO, ::MPS)`

### ISSUE THREAD

**Issue by GTorlai** [ITensor/ITensors.jl#422]
There is a memory problem in the contraction between an MPS and an MPO using the default "densitymatrix" method:

```julia
function test(N)
  sites = siteinds("S=1/2",N);
  mps = randomMPS(sites);
  mpo = randomMPO(sites);
  @time mpo * mps;
end
```
The result is:
```
N = 8	0.003883 seconds (14.31 k allocations: 3.249 MiB)
N = 9	0.006476 seconds (16.38 k allocations: 8.588 MiB)
N = 10	0.017550 seconds (18.46 k allocations: 29.048 MiB)
N = 11	0.079618 seconds (20.55 k allocations: 109.751 MiB)
N = 12	0.691359 seconds (22.64 k allocations: 431.062 MiB)
N = 13	6.165078 seconds (24.74 k allocations: 1.673 GiB)
N = 14	58.80654 seconds (26.84 k allocations: 6.678 GiB)
```

The test works fine with `*(mpo,psi,method="naive")`.

**Comment by emstoudenmire** [comment]
Hi Giacomo,
Thanks for the report: by a memory problem are you meaning that the memory amounts reported on the right hand side (by @time) are larger than expected? Note that those numbers are total memory allocated integrated over the whole routine, not peak memory usage.

**Comment by GTorlai** [comment]
Yes. Ok, I see. I caught this with the (exponential?) scaling in the runtime, and when I saw the memory allocation, I assumed that was the problem. However, I'm not entirely sure.

**Comment by emstoudenmire** [comment]
Oh ok I see what you mean now about the exponential scaling. You're right that these algorithms should all scale only linearly with system size. But I have a strong suspicion of what's going wrong here, which is that the density matrix algorithm was only tested with truncation turned on; the non-truncating case takes a bit of extra care to remain linear scaling (one has to feed in by hand information about the maximum rank of the density matrices). So that's probably not being handled in the right way. It will be a good thing to have fixed - thanks!

**Comment by mtfishman** [comment]
This can be fixed in two ways:
- Set the default cutoff to something very small, like 0 or 1e-15.
- Set the default maximum bond dimension to the product of the input MPS/MPO bond dimensions.

Setting the cutoff may be less numerically sound, since if the cutoff is set to zero, the eigenvalues may not end up being exactly zero (so it may not truncate enough), or if it is set to something very small like 1e-15, it may truncate "important" eigenvalues. However, setting the default maximum bond dimension may mean the final MPS bond dimension ends up being larger than what is strictly needed. Perhaps the most "rigorous" way is to default to setting cutoff = 0 and the maximum bond dimensions to the product of the MPS/MPO bond dimensions.
