### ISSUE TITLE
(no)prime not working appropriately with <keyword arguments>

### ISSUE THREAD

**Issue by phymann** [ITensor/ITensors.jl#484]
Here is a minimal example to reproduce this bug:
```
N = 3
sites = siteinds("S=1/2",N)
psi = randomMPS(sites,2)
@show inds(noprime(prime(psi[2]),commoninds(psi[2],psi[3])));
```
I would expect that in this case `noprime` removes the prime of Link index that connects "Site = 2" and "Site = 3". However it does nothing.

This type of bug also occurs if one use `prime` instead of `noprime`. It seems that `<keyword arguments>` does not work appropriately.

**Comment by phymann** [comment]
BTW, I just find
`prime(prime(psi[2],commoninds(psi[2],psi[3])))`
will work as expected, while
`prime(prime(psi[2]),commoninds(psi[2],psi[3]))`
won't.

**Comment by orialb** [comment]
Looking at the docstring of `noprime` I think maybe the way you are trying to use it is not the intended way, or at least it is undocumented (but I'm not sure, Miles or Matt will have to comment whether it's correct or not).

One documented way to achieve what you are trying to do is: 
```julia
noprime(prime(psi[2]); tags = "l=2")
```
i.e. use the `tags` keyword to filter which indices are acted on.

Another way which works, but I don't know if this is really an intended way for this to work or just an incidental result of generic programming is
```julia
l = commoninds(psi[2],psi[3])
noprime(prime(psi[2]), prime(l))
```
The reason why it doesn't work without priming `l` is because it eventually calls `noprime(is::IndexSet, l::IndexSet)` which in turn calls `setprime(fmatch(l), is)`. This will change the prime level only for those indices in `is` which are in `l`. But since in this case all the indices in `is` (`==inds(prime(psi[2]))`) are primed and the indices in `l` are not primed it will not match any indices.

**Comment by emstoudenmire** [comment]
Thanks for reporting this. Also thanks @orialb for the useful comments about how to get the desired behavior.

@phymann my understanding of what's happening here is that, while you are acting with `noprime` on a "primed" MPS tensor `prime(psi[2])`, you are obtaining the common index from the unprimed `psi[2]` and `psi[3]` tensors. So then the Index that you are providing to `noprime` is unprimed and doesn't match any of the indices of `prime(psi[2])`, all of which have a prime level of 1. Since it doesn't match any of the indices (because Index objects have to have the same id, prime level, and tags to compare equal) there is no effect, which is the intended behavior.

If you were to change your code to

    @show inds(noprime(prime(psi[2]),commoninds(psi[2],psi[3])'));

then you should get the effect you want I believe. (Note the extra ' after commoninds above.)

**Comment by phymann** [comment]
Thanks both @orialb and @emstoudenmire . I got your points and realize my problem here.
Basically <keyword arguments> does not work because it does not find any indices match, literally.
