### ISSUE TITLE
Add `1 ./ A` broadcasting operation for ITensor

### ISSUE THREAD

**Issue by mtfishman** [ITensor/ITensors.jl#493]
Define `1 ./ A` for an ITensor, which would be the same as `A .^ -1`.

**Comment by mtfishman** [comment]
Also, we may want to add `A ./ B` as elementwise division of two ITensors with the same indices. Also, we should define a Hadamard product of two ITensors, maybe with the symbol `∘` (`\circ`).

**Comment by emstoudenmire** [comment]
Yes in principle to all of these, though for ones like `A ./ B` I'd recommend we have an application in mind, even if it's not one we are doing currently. Otherwise there might be code that gets introduced but not well maintained.

The Hadamard product would be very welcome I think, because as you know in certain corners of tensor mathematics it's extremely common, so might be surprising for people looking at ITensor if it's not there. The Khatri-Rao product is closely related, I think, but involves grouping indices in various ways so it could be a future extension (maybe just a function call).

**Comment by mtfishman** [comment]
I was on the fence about `A ./ B`, but Giacomo had an example of wanting to use that when implementing optimizers for gradient optimization of tensor networks.

**Comment by emstoudenmire** [comment]
Ok good - just wanted to check there was some sense of how it might be used, so it doesn't lead to any surprises or unmaintained code. But I think that the notation and meaning is clear, so as long as we can foresee at least one use case I'm for it.

**Comment by mtfishman** [comment]
Closed by #495.
