### ISSUE TITLE
More general state function

### ISSUE THREAD

**Issue by mtfishman** [ITensor/ITensors.jl#503]
For many applications, it would be helpful to have a more general definition of `state`, where it can be any vector/order-1 tensor (not just a certain nonzero element, like it represents now). For example, for a "Qubit" site type, it would be helpful to be able to initialize a product state in an arbitrary basis, i.e.:
```julia
s = siteinds("Qubit", 4)
psi = productMPS(s, ["X+", "X-", "X+", "X-"])
```
Unfortunately, this doesn't quite fit into the paradigm of the current use of `state`, where it represents a single nonzero element/an Index set to a certain value.

One proposal for generalizing this would be to make `state` define an order-1 ITensor, i.e.:
```julia
import ITensors: space, state

space(::SiteType"Qubit") = 2

state(::StateName"X+", ::SiteType"Qubit", s::Index) = itensor([1/sqrt(2); 1/sqrt(2)], s)
state(::StateName"X-", ::SiteType"Qubit", s::Index) = itensor([1/sqrt(2); -1/sqrt(2)], s)

# productMPS would call the version of state above:
s = siteinds(4, "Qubit")
psi = productMPS(s, ["X+", "X-", "X+", "X-"])
```
Now, this would of course be breaking, since then it wouldn't be clear when the output of `state` should be an ITensor or just a value. We could introduce another function for the current usage of `state`, such as `val`:
```julia
import ITensors: val

val(::ValName"0", ::SiteType"Qubit") = 1
val(::ValName"1", ::SiteType"Qubit") = 2

s = siteind("Qubit")
T = ITensor(s)
T[s => "0"] = 1.2
T[s => "1"] = 2.4
```
I think something like `val` is a better name than `state` anyway for this usage, since `val` indicates it is used as the value of an IndexVal.

@emstoudenmire, let me what you think about this design change. We can also consider keeping the current usage of `state` the same, and think of another name for making an order-1 ITensor (like just using `op` in some way), but I can't really think of better names than the ones I'm proposing above.

**Comment by mtfishman** [comment]
One name I can think of as an alternative would be `initstate`, however it wouldn't always be used in the context of initializing a product state. But we could use that as an intermediate name and decide to make a breaking change later.

**Comment by emstoudenmire** [comment]
This is a good insight about how we could push the design a little bit to handle a lot more interesting cases. Also I'm sure you recall we have sometimes wanted to abuse the `op` function a bit to have it return single-index tensors in some cases (such as when wanting to project a site of an MPS to a definite state, like when sampling from an MPS). But I agree `op` would not be an approprite name for a single-index tensor, whereas `state` is a great name because it works even outside of physics. Like if one was doing machine learning of grayscale images, one could define a black state, gray state, and white state of a pixel. And `val` makes about equal sense to `state`, probably more for returning an IndexVal.

So there's really just the issue of backward compatibility, and I think here we probably have few users calling `state` directly in the current version. They are probably only using it through the `productMPS` interface indirectly.

So I approve of making this change!

**Comment by mtfishman** [comment]
Glad you approve, thanks for the quick and detailed response. That's an interesting point about how this would be useful for machine learning applications. I'll go ahead with this, we will be using this for PastaQ as well.

**Comment by mtfishman** [comment]
I think a good way to go would be to implement this and possibly a few other breaking changes, and make it a v0.2.0 release.

**Comment by emstoudenmire** [comment]
Yes agreed we should update to 0.2.0 if we make this change, and then include any other breaking changes on the to-do list. I think lightly breaking changes like this, and perhaps the `qn` function, are not too disruptive because there are probably only 1 or at most 2 users using these functions directly right now and it would be easy for them to update their codes anyway.

**Comment by emstoudenmire** [comment]
So while a recent PR I merged (#664) does implement the above redesign, it occurred to me in the course of implementing Index=>String pairs for ITensor get and set index that this new design could lead to some awkward or surprising behaviors. The issue revolves around two different, but totally reasonable, meanings of the function name `val`. They are:

1. `val` means "return only the value part of an IndexVal", for example `val(s[1]) == 1`
2. `val` means "make an IndexVal out of this thing" for example `val(s,"Up") == val(s=>"Up") == IndexVal(s,1)`

The awkward part is that it leaves a situation where `val(s,1)` returns an `IndexVal` while `val(s[1])` and `val(s=>1)` both return an integer.

Is this a problem or not? If it is a problem, what is the better design we want? We could come up with different names for the above two cases, or switch one of them out.

A good solution might be to make `val(s,1)` and `val(s,"Up")` return an *integer* instead of an IndexVal. The idea would be that users are less likely to want IndexVals themselves, but use them more often implicitly, like through code such as `T[s=>"Up"]`.

If users do want an IndexVal from a string, we can then add support for things like the following:

- `s["Up"] == IndexVal(s,1)`
- `IndexVal(s,"Up") == IndexVal(s,1)`

**Comment by mtfishman** [comment]
Definitely agree that `val(s, 1)` shouldn't make an `IndexVal`. The design you are proposing sounds like a good way to go.

On a kind of side note, I find it a bit confusing how many different ways there are to make an `IndexVal`. There are:

1. `IndexVal(i, 2)`
2. `i(2)`
3. `i[2]`
4. `i => 2` (which doesn't technically make and `IndexVal`, but is always supposed to act like an `IndexVal`).

Can we cut this down and make it more consistent in the code? My preference is that `i => 2` is the "official" interface, and then internally we always convert that to `IndexVal` where needed (which is more of an internal detail and not exposed to the user). I always have to remind myself what `i(2)` and `i[2]` means when I read the code.

**Comment by emstoudenmire** [comment]
It's a good point & I agree we should simplify. One obvious one that can go soon is the `i(2)` notation, which i only put in just to ease the transition of code from C++ to Julia. The 0.2 release would be a good time to put a deprecation warning on it or drop it altogether.

Realistically we could get away with just `IndexVal(i,2)` and `i=>2`, it's just that then we are only left with one rather verbose way to actually make an IndexVal and one nice notation but which has the downside of not actually making an IndexVal. All I'm saying is it's too bad that `i=>2` doesn't make an IndexVal right away.

Let's think about it some more. We could go as far as just using `Pair{Index}` instead of `IndexVal`, but I think we may be getting some value out of having IndexVal to be a distinct type. It's worth thinking through.

**Comment by mtfishman** [comment]
I think it is ok to have the verbose `IndexVal(i, 2)` as the only way to construct an actual `IndexVal`, since it should only be used internally and makes the code more self documenting. Users should really only ever need to use `i => 2` notation.

I would definitely consider defining `IndexVal` as `Pair{Index, Int}`, but we can make that change later. I think it would be quite similar to our recent move of removing `IndexSet` in favor of `Tuple{Vararg{Index}}`/`Vector{<:Index}`, but the `IndexVal` version will be much simpler. My understanding is that we very rarely need to construct `IndexVal`s anyway, even internally.
