### ISSUE TITLE
Extra backslash in `op` docstring

### ISSUE THREAD

**Issue by emstoudenmire** [ITensor/ITensors.jl#529]
When viewing the docstring for the `op` function in the Documenter output, there are extra backslashes in the part talking about combining operators using the `*` symbol.

**Comment by mtfishman** [comment]
I added those because without escaping `*`, on my computer the `*` wasn't being shown and was causing some strange formatting (it seemed like the `*` was being interpreted as some sort of markdown formatting). I tried adding a single backslash, which caused an error, so I added 2 backslashes based on a discourse thread I found about properly escaping characters in docstrings. 

However, I also added backticks around the expressions that were using `*`, which might make the backslashes unnecessary now.

**Comment by mtfishman** [comment]
Ok, should be fixed on master now.

**Comment by emstoudenmire** [comment]
Thanks - I was planning to fix this one if you didn't have time but appreciate the quick fix!
