### ISSUE TITLE
IndexSet docs are outdated and need more details

### ISSUE THREAD

**Issue by tomohiro-soejima** [ITensor/ITensors.jl#541]
[The documentation of `setdiff`](https://itensor.github.io/ITensors.jl/stable/IndexSetType.html#Base.setdiff-Tuple{IndexSet,IndexSet}) says "Output the IndexSet with Indices in A but not in the IndexSets Bs." However, it returns `Array{Index{Int64}, 1}`.

Here is the MWE tested with `v0.1.30`.

```
i = Index(2)
j = Index(2)
k = Index(2)
set1 = IndexSet(i, j,k)
set2 = IndexSet(i)
@show setdiff(set1, set2)
@show setdiff(set1, set2) |> typeof
```

Output:
```
setdiff(set1, set2) = Index{Int64}[(dim=2|id=651), (dim=2|id=72)]
setdiff(set1, set2) |> typeof = Array{Index{Int64},1}
```

**Comment by mtfishman** [comment]
Hi,

Unfortunately the documentation is a bit outdated, and the documentation for IndexSets is pretty lacking. However, at the moment the behavior you see is intended.

The short answer is that the high level interface for `IndexSet`s has ITensor-specific names for set operations, such as:

- `uniqueinds` (similar to `setdiff`)
- `commoninds` (similar to `intersect`)
- `noncommoninds` (similar to `symdiff`)
- `unioninds` (similar to `union`)

Those should generally be used for ITensor objects, which we should make more clear. Docs for these can be found in the `ITensor` docs section here: https://itensor.github.io/ITensors.jl/stable/ITensorType.html#IndexSet-set-operations-1 (which should be copied over to the `IndexSet` section as well).

Those functions also work on `IndexSet`s, and return an `IndexSet` instead of a vector of indices. 

Part of the reason for the discrepancy is to have the Julia Base functions like `setdiff` match more with their behavior for Julia types like tuples:
```julia
julia> setdiff((1, 2, 3), (2,))
2-element Array{Int64,1}:
 1
 3
```
For the sake of the Base set functions, IndexSets act more like Tuples of indices:
```julia
julia> i = Index(2)
(dim=2|id=732)

julia> j = Index(2)
(dim=2|id=946)

julia> k = Index(2)
(dim=2|id=604)

julia> setdiff((i, j, k), (i,))
2-element Array{Index{Int64},1}:
 (dim=2|id=946)
 (dim=2|id=604)

julia> setdiff(IndexSet(i, j, k), IndexSet(i))
2-element Array{Index{Int64},1}:
 (dim=2|id=946)
 (dim=2|id=604)

julia> setdiff((i, j, k), IndexSet(i))
2-element Array{Index{Int64},1}:
 (dim=2|id=946)
 (dim=2|id=604)

julia> uniqueinds(IndexSet(i, j, k), IndexSet(i))
IndexSet{2} (dim=2|id=946) (dim=2|id=604) 
```
There are a few reasons for this design choice, some of which are slightly technical. Essentially, in some ways IndexSets act like sets, but they are more closely related to statically sized containers like `Tuple`s, and the set interface is more a convenience layer. In general, at a high level we've tried to make `IndexSet`s and `Tuple`s of ITensor `Index` objects interchangeable, which would create a tension with Julia's Base behavior for functions like `setdiff`. Julia could in theory make functions like `setdiff` return a tuple for tuple inputs, but it makes more sense to output a vector since the operation is inherently dynamic, i.e. the size of the output can't be determined before running the function.

I'll work on clarifying the docs, let me know if you have any other questions about this.

-Matt

**Comment by mtfishman** [comment]
The IndexSet docs are improved on master, so I'll close this.

**Comment by tomohiro-soejima** [comment]
Thanks for the detailed explanation! The design choice makes sense.
