### ISSUE TITLE
Do not convert element types to float

### ISSUE THREAD

**Issue by GiggleLiu** [ITensor/ITensors.jl#612]
```julia
julia> ITensor(TropicalF64.(randn(3,3)), i, j)
ERROR: DimensionMismatch("In ITensor(::Array, ::IndexSet), length of Array (9) must match total dimension of IndexSet (1000000)")
Stacktrace:
 [1] itensor(A::Matrix{TropicalF64}, inds::IndexSet{Index{Int64}})
   @ ITensors ~/.julia/dev/ITensors/src/itensor.jl:363
 [2] ITensor(A::Matrix{TropicalF64}, inds::IndexSet{Index{Int64}})
   @ ITensors ~/.julia/dev/ITensors/src/itensor.jl:394
 [3] ITensor(::Matrix{TropicalF64}, ::Index{Int64}, ::Vararg{Index{Int64}, N} where N)
   @ ITensors ~/.julia/dev/ITensors/src/itensor.jl:396
 [4] top-level scope
   @ REPL[1]:1
```

The relevant code

https://github.com/ITensor/ITensors.jl/blob/ae84b80ef55271dca1aa39dfcd4db350c4e864e1/src/itensor.jl#L364

Wondering if it is plausible to remove this element type conversion?

**Comment by mtfishman** [comment]
The error you are getting seems unrelated to the floating point conversion. What are the dimensions of the indices `i` and `j` there? You should have `dim(i) * dim(j) == 9` to match the length of the input data.

I also don't see why that conversion should be a problem for `Matrix{TropicalF64}`. It looks like you need to define the proper conversions for `Tropical` to make that work:
```julia
julia> using TropicalNumbers

julia> M = TropicalF64.(randn(3,3))
3×3 Matrix{TropicalF64}:
 -0.12183766395025368ₜ   0.3375039927258362ₜ  0.11302141015062543ₜ
  0.38362837549834655ₜ  0.22892984628787322ₜ   -0.467953584336932ₜ
 -0.19956589737193936ₜ  -0.2930410395796062ₜ  -0.6225988124988838ₜ

julia> float(M)
ERROR: MethodError: no method matching AbstractFloat(::TropicalF64)
Closest candidates are:
  (::Type{T})(::T) where T<:Number at boot.jl:760
  (::Type{T})(::AbstractChar) where T<:Union{AbstractChar, Number} at char.jl:50
  (::Type{T})(::Base.TwicePrecision) where T<:Number at twiceprecision.jl:243
  ...
Stacktrace:
 [1] float(x::TropicalF64)
   @ Base ./float.jl:206
 [2] float(A::Matrix{TropicalF64})
   @ Base ./float.jl:896
 [3] top-level scope
   @ REPL[57]:1

julia> Base.AbstractFloat(t::Tropical{T}) where {T} = Tropical{float(T)}(t)

julia> float(M)
3×3 Matrix{TropicalF64}:
 -0.12183766395025368ₜ   0.3375039927258362ₜ  0.11302141015062543ₜ
  0.38362837549834655ₜ  0.22892984628787322ₜ   -0.467953584336932ₜ
 -0.19956589737193936ₜ  -0.2930410395796062ₜ  -0.6225988124988838ₜ
```
Then I think that ITensor constructor should work fine.

Even beyond your particular case, it may be worth revisiting how this constructor works. For some background on that conversion, the use case for that was people inputting something like `ITensor([0 1; 1 0], i, j)` as a quick way to construct an X-gate, but in a vast majority of cases they really wanted a floating point tensor. If we didn't convert right away in this case, it could lead to problems where internally either we:

1. Have to detect integer types are being used and convert to floating point to dispatch to BLAS, which would happen every time that ITensor is being used which doesn't seem ideal (so better off converting right up front).
2. Don't convert to floating point at all and then it falls back to a slow generic gemm call.

A solution could be to special case for `<: Integer` for that conversion. Maybe that causes problems for someone who wants to use `BigInt` though. For other versions of the constructor you can explicitly put the element type as the first input, for example:
```julia
julia> i, j = IndexSet(_ -> Index(2), 2);

julia> @show ITensor(i, j);
ITensor(i, j) = ITensor ord=2
Dim 1: (dim=2|id=897)
Dim 2: (dim=2|id=129)
NDTensors.Dense{Float64, Vector{Float64}}
 2×2
 0.0  0.0
 0.0  0.0

julia> @show ITensor(Int, i, j);
ITensor(Int, i, j) = ITensor ord=2
Dim 1: (dim=2|id=897)
Dim 2: (dim=2|id=129)
NDTensors.Dense{Int64, Vector{Int64}}
 2×2
 0  0
 0  0
```
We could also add the same thing for this type of constructor so someone could do `ITensor(Int, [0 1; 1 0], i, j)` if they really wanted an integer. I think it seems reasonable to allow a way to opt-in.

**Comment by GiggleLiu** [comment]
Thanks for your reply. Unfortunately, there is no conversion between Tropical and Float. I think there is no need to help user change the element type to float. I never wrote something like
```julia
ITensor([0 1; 1 0], i, j)
```

Instead, I will use
```julia
ITensor([0.0 1; 1 0], i, j)
```

I think it is inside most programar's gene, we do not need to worry about it. On the other side, if the program does the conversion automatically when I really want Integer algebra, it can be hard to debug.

**Comment by mtfishman** [comment]
I edited the proposal above so that it only requires overloading `Base.float(t::Tropical)` instead of `Base.AbstractFloat`. I think it is reasonable to define `float(::Tropical)` to mean the closest floating point version of the given tropical number. Note that it is not a conversion to something like `Base.Float64`, it still keeps it as a `Tropical` number. This is similar to the definition of `float` for other number types, like `Complex` or `Quaternion`:
```julia
julia> i = Complex(1, 2)
1 + 2im

julia> float(i)
1.0 + 2.0im

julia> using Quaternions

julia> i = Quaternion(1,2,3,4)
Quaternion{Int64}(1, 2, 3, 4, false)

julia> float(i)
Quaternion{Float64}(1.0, 2.0, 3.0, 4.0, false)
```

**Comment by mtfishman** [comment]
@GiggleLiu, I believe the `Base.float(::Tropical)` overload would fix this issue for you without having to change the ITensor constructor. It seems like a reasonable definition to have, do you have a reason why you wouldn't want to add it?

If you really want integer storage we can also provide an interface where the element type can be specified. To be honest, I've never heard of a case where integers were used in tensor network calculations, do you have a use case in mind?

**Comment by GiggleLiu** [comment]
> do you have a reason why you wouldn't want to add it?

It is is not the purpose of float. I do have some using cases:

Using tensor network to solve the 3-coloring problem and 3-coloring. https://arxiv.org/pdf/1708.00006.pdf

**Comment by mtfishman** [comment]
That seems exactly the purpose of the `float` function, what would be your interpretation of `float(::Tropical)`?

**Comment by GiggleLiu** [comment]
float should return a floating point number I think. Tropical is not a subtype of AbstractFloat

**Comment by mtfishman** [comment]
My interpretation of `float` is that it returns the closest floating point version of whatever object you put in. It has a wider usage than literally converting to a subtype of `AbstractFloat`. For example with `Quaternion`:
```julia
julia> using Quaternions

julia> i = Quaternion(1,2,3,4)
Quaternion{Int64}(1, 2, 3, 4, false)

julia> f = float(i)
Quaternion{Float64}(1.0, 2.0, 3.0, 4.0, false)

julia> f isa AbstractFloat
false
```
This seems exactly analagous to the case of `Tropical`. In general, any custom number type that is parametrized wouldn't be a subtype of `Integer`/`AbstractFloat`, but it still makes sense to define the generic concept of converting to the closest floating point type with `float`.

Anyway, besides this particular debate about `Tropical`, I see that the `float` conversion can be troublesome for custom types, since we probably don't in general want to assume that every element type input into that constructor has a float conversion or that float conversion is desirable (even if in the case of `Tropical` I think defining `float` makes sense, it is still an imposition on external packages).

I think in a vast majority of cases of just typing `itensor([0 1; 1 0], i, j)` people would really want a floating point ITensor, but for more "exotic" element types there was probably a particular reason for choosing that type. Perhaps a compromise for now would be to only perform the conversion for the case of `Array{<: Int}`. In addition, I can add the API where the element type can be explicitly specified by the first argument.
