### ISSUE TITLE
memory issue

### ISSUE THREAD

**Issue by zhendongli2008** [ITensor/ITensors.jl#85]
Hi guys,

It is really nice to see the use of julia for DMRG. I've tried the code a little bit
and observed that currently the memory usage is large for a relatively
'small' (am I right?) test (examples/dmrg/1d_Heisenberg_dmrg.jl).

 **17.823825 seconds (3.94 M allocations: 26.225 GiB, 13.91% gc time)**

My question is that is it because the current code has not been
carefully written to avoid the unnecessary memory allocation or it is the julia
compilation that took a large amount of memory. If the later is
the case, then it might be a problem. 

PS: Another question is that about the speed compared with the
c++ version of itensor. Does any benchmark have been performed?
Any comment or insight about this will be very helpful for my understanding.
Thanks!

Best,
Zhendong

julia> @time include("1d_Heisenberg_dmrg.jl")
sweeps = Sweeps
1 cutoff=1.0E-10, maxdim=10, mindim=1
2 cutoff=1.0E-10, maxdim=20, mindim=1
3 cutoff=1.0E-10, maxdim=100, mindim=1
4 cutoff=1.0E-10, maxdim=100, mindim=1
5 cutoff=1.0E-10, maxdim=200, mindim=1

After sweep 1 energy=-137.331806906147 maxDim=9 time=0.099
After sweep 2 energy=-138.933671055011 maxDim=20 time=0.386
After sweep 3 energy=-138.940063572147 maxDim=85 time=2.773
After sweep 4 energy=-138.940085657916 maxDim=100 time=6.140
After sweep 5 energy=-138.940086065305 maxDim=99 time=7.619
Final energy = -138.94008606530534
 17.823825 seconds (3.94 M allocations: 26.225 GiB, 13.91% gc time)

**Comment by emstoudenmire** [comment]
Hi Zhendong,
Just as a short answer, though we could discuss more, the answer to your questions are:
- the memory usage you see is not because the ITensor code has not been carefully written. It has been carefully written but what you are seeing has to do with both the Julia JIT compiler and the way @time reports memory usage
- however, this is not a problem because I think it's just the way @time reports memory usage, not that Julia is using a large amount of memory at any one time

We could both look into this more, for example, by looking at a system monitor such as top to confirm that at no point is the code using a very large amount of memory. I think, rather, that it's just adding up all of the allocations which are done and reporting the total amount of memory provided by the allocator (not counting that much of it was deallocated before more was allocated). 

About speed, we have been doing some benchmarks against the C++ version and we are very pleased. Here is what we have found:
- when using MKL as the BLAS (not Julia's default by the way), we can barely see any difference between speed of tensor contractions and tensor additions between our C++ and Julia versions
- for DMRG specifically, we see that for bond dimensions around 200 and a 100 site S=1 chain, the Julia version is about 1.2x slower than our C++ version. We think a lot of this is due to overhead which scales sub-leadingly with bond dimension (so *not* as m^3)
- for larger bond dimension DMRG, such as for 2D, we can barely measure any time difference between the Julia and C++ version

Definitely for smaller runs, like small bond dimension DMRG, the initial JIT compilation time is noticeable. This is something the Julia developers have said is now their main priority since they just finished overhauling how multithreading works in Julia.

Ok happy to discuss more since this is something we are working to understand too -

Miles

**Comment by zhendongli2008** [comment]
Hi Miles,

Thank you for your response. I just got into julia recently, and your
clarification helps a lot.
Now I see the report by @time is indeed quite misleading. Using top, I
found the calculation
took O(100MB) memory for the same test. Looking into the manual of julia, I
found the slicing
operation is quite uncommon, since it alway creates a new array, which can
lead to memory
issues. I guess this has been taken into account in itensor.

Your data about speed look quite promising. I'm writing some codes to test
the speed also.
Apart from that, I did some tests on other aspects, such as HDF5.jl, which
seems to be slower
than the python interface in reading and writing. Hopefully, this is due to
my own misunderstanding,
and I will try to found out the problems. Good to discuss these issues with
you!

Best,
Zhendong

Miles <notifications@github.com> 于2019年8月20日周二 上午11:32写道：

**Comment by orialb** [comment]
> Definitely for smaller runs, like small bond dimension DMRG, the initial JIT compilation time is noticeable. This is something the Julia developers have said is now their main priority since they just finished overhauling how multithreading works in Julia.

A possible workflow to mitigate this when doing a lot of short calculations is just keeping a REPL session open as long as posisble (or batching together several short calculations when running on a cluster, which is something you will anyway want to do if the calculations are very short). I personally don't think it's a real issue. 

For the example above if I run the script up to the point of calling dmrg in the REPL then:
```julia
julia> maxdim!(sweeps,5,5,5,5,5)

julia> @time dmrg(H,psi0,sweeps)
After sweep 1 energy=-135.864926480553 maxDim=5 time=4.526
After sweep 2 energy=-136.921421287689 maxDim=5 time=0.139
After sweep 3 energy=-137.097389047607 maxDim=5 time=0.138
After sweep 4 energy=-137.189548183009 maxDim=5 time=0.139
After sweep 5 energy=-137.225590439081 maxDim=5 time=0.142
 10.923111 seconds (26.05 M allocations: 1.522 GiB, 6.56% gc time)

julia> @time dmrg(H,psi0,sweeps);
After sweep 1 energy=-135.864926480553 maxDim=5 time=0.121
After sweep 2 energy=-136.921421287689 maxDim=5 time=0.142
After sweep 3 energy=-137.097389047607 maxDim=5 time=0.129
After sweep 4 energy=-137.189548183009 maxDim=5 time=0.133
After sweep 5 energy=-137.225590439081 maxDim=5 time=0.132
  0.661637 seconds (2.27 M allocations: 372.735 MiB, 12.20% gc time)
```
So you pay the price of compilation only once when you start the REPL session and then you can keep running your short calculations without the extra cost.

**Comment by emstoudenmire** [comment]
Thanks for the discussion Zhendong & Ori. Those timings are helpful to see. Zhendong: it's good to know that top only showed about 100Mb of memory usage.
