### ISSUE TITLE
[ITensors] [BUG] Performance of apply for second-neighbor gates

### ISSUE THREAD

**Issue by emstoudenmire** [ITensor/ITensors.jl#892]
**Description of bug**

For the case of gates which are second neighbor (an example being in the MPS version of purification finite T algorithm), the performance and scaling of `apply` seems to be far from optimal.

**How to reproduce**

Here are some bits of code that show how to reproduce:

```julia
gates = ops([("expτSS", (n, n + 2), (τ=-δτ / 2,)) for n in 1:2:(L - 2)], s)
append!(gates, reverse(gates))
# "exptSS" makes a Heisenberg time evolution gates on sites n, n+2
...
for τ in 0:δτ:(beta_max / 2)
   psi = apply(gates, psi; cutoff, move_sites_back=false)
end
```
It is slow even with `move_sites_back=false`, taking as long as 200s for the case of an MPS with 28 sites (physical size 14 in the purification method).

**Version information**

Version 0.3.0 of ITensors

**Comment by mtfishman** [comment]
Thanks for the report Miles, quite a bad performance bug!

Something that would be helpful both for diagnosing this issue and also in general would be adding `Observer` support to the `apply` function. It would be very helpful to save the bond dimension, site permutation, number of swaps, etc. into an Observer so we can investigate what's going on here, since I imagine it is related to the swap gate strategy we're using now.

**Comment by emstoudenmire** [comment]
Good suggestion about the Observer – should be easy to try with the new Observers.jl design!
