### ISSUE TITLE
time evolution 

### ISSUE THREAD

**Issue by orialb** [ITensor/ITensors.jl#98]
Hi,
I am interested in adding some time evolution functionality to the package (since this is my main use case at the moment). Will you be interested in such a contribution or is it something you prefer to postpone for later stages / prefer not to delegate to external contributors ?

**Comment by mtfishman** [comment]
Thanks for asking! I think time evolution is a subtle thing to have in the main repository, we are thinking of the main repository (ITensors.jl) as having a lot of low level tools as well as very established MPS methods like MPO*MPS and DMRG. In the C++ library, the only official time evolution we support (and wanted to redesign anyway) was a function to apply a set of 2-site gates to an MPS to specified locations, which is just a helper function that basically calls `replaceBond!` with a few extra efficiencies built in. This mostly covers TEBD (but is still appropriate for the main package, since it is a general tool useful for many tensor network applications).

I am guessing you are thinking about TDVP support? I think something like that would be better left for a separate package (that can of course use ITensors.jl as a dependency and reexport ITensors). We would like to have an "official" TDVP add-on package (which we have some preliminary work on in C++). We are of course happy to get external contributions, I think for now it would be best if you started your own time evolution package based on ITensors.jl and when you want we can advertise it in some way (like through our "codes" page: http://www.itensor.org/docs.cgi?page=codes).

I think the best thing for contribution to ITensors.jl would be low level tools that are needed for time evolution/TDVP. For example, for TDVP it is important to make sure that `ProjMPO` is flexible enough to handle various unit cell sizes (I believe it is right now). Additionally, it is important to use Krylov-based methods to apply the exponential of the projected MPO to the projected wavefunction, it would be useful to have that in ITensors.jl.

Cheers,
Matt

**Comment by orialb** [comment]
Hi Matt,
thanks for the detailed reply. 

>  I think time evolution is a subtle thing to have in the main repository

got it, that makes sense. On the long run I think it would be great to have a collection of such ITensor extensions under one Github organization , like is done in other popular julia packages. But I guess one first has to develop the extensions and decide whether they are worthy of the brand :) 

> I am guessing you are thinking about TDVP support?

I actually wanted to start with converting my TEBD code to ITensor (my use case is for open systems dynamics where it's not clear to me that one method is always better than the other). 

> Additionally, it is important to use Krylov-based methods to apply the exponential of the projected MPO

I think that I checked and the methods from KrylovKit.jl seem to just work with ITensors ,but I guess you would like to have your own method for exponentiation ? Any idea of a specific algorithm you would want to be included for exponentiation ?  

For TEBD- would it make sense to have an `exp(t::ITensor, Li::IndexSet, Ri::IndexSet)` function for an ITensor (which works only when `Li,Ri` have the same overall dimension) so one can easily create the bond gates for exp(i*dt*H)?

> I think for now it would be best if you started your own time evolution package based on ITensors.jl 

Ok, I will start working on it then :) 

p.s
When are you planning of registering the package? It seems that many packages are registered already when they are in early stages (and ITensors.jl seems already quite functional at the moment).

**Comment by orialb** [comment]
My idea was to just apply `LinearAlgebra.exp` function to the storage, similar to the way other operations are currently implemented.  `exp` handles both hermitian and non-hermitian cases so there is no need to differentiate between the two cases with this kind of implementation.

**Comment by mtfishman** [comment]
That seems fine.

**Comment by orialb** [comment]
ok. I guess this issue can be closed now. I will open specific issues for the relevant features that will come up when working on the time evolution code.

**Comment by emstoudenmire** [comment]
Just chiming in to say thanks for asking about these things, Ori, so you can be sure that your work will be properly placed with relation to the main ITensors.jl repo versus an organization repo etc. It's definitely helpful to check with us ahead of time on these things.

As Matt mentioned, we would probably like to have some elementary 2-site-gate code included in ITensors.jl, based on the one we have in the C++ version but improved to have a better interface and yet work as generally and efficiently as possible. As you know, such code would cover most of what one needs to TEBD, though I can imagine a black-box TEBD wrapper and helper functions for making gates would be very helpful.

We might also use such a gate-application code internally. For example, we are planning to offer a more sophisticated set of `randomMPS` functions which make random MPS's by applying random circuits of a certain depth and layout to a reference product state. It would be a very nice and helpful thing to have (for example, for robust unit tests or for initializing various MPS algorithms in an unbiased way).

I could imagine such a code also being a workhorse for quantum computing applications.

For TDVP and other things, as Matt already said, we'd like to approach that more gradually, by having a few external implementations then letting them each mature.

One other comment on KrylovKit is that we would like to consider using it more, but the documentation is just rather sparse at this point so I had a hard time using it properly. I got it working but the results were not good, very probably because I was using it incorrectly.

**Comment by orialb** [comment]
Thanks for your reply Miles. 

> helper functions for making gates would be very helpful

Yes, I think having an option to build the bond gates in a similar way to the interface for adding operators to `AutoMPO` would be really great and would make it super easy for users to quickly explore new models.  I guess the data contained in `AutoMPO` is enough to implement this, but maybe it's better to have a separate object (like `AutoBondGates` or some better name) to avoid confusion. I will try to prototype this when writing the TEBD code.

> As you know, such code would cover most of what one needs to TEBD

I have a semi-related question. As far as I understand there are some numerical differences between tDMRG , which I think is what is currently the easiest to implement using the MPS interface in ITensors, and TEBD where one always stores the site tensors in a fixed canonical form but also keeps track of the singular-values. So far I have been using TEBD (with the trick to avoid multiplying by `S^{-1}` ). Do you know if these two methods are numerically equivalent in practice, or whether one is strictly better than the other? I'm asking because I'm trying to figure out whether there is a reason to support both methods.

**Comment by Jutho** [comment]
Just to chime in, let me know if there is anything I can do to improve KrylovKit.jl or its documentation, and of course, improvements and additions are always welcome. I am certainly also no expert on Krylov methods.

@emstoudenmire , what do you mean by "results were not good"? In terms of performance, or in terms of actual numerical values being returned?

**Comment by emstoudenmire** [comment]
Hi Jutho, thanks for checking in on this. First off, I hope it's clear I wasn't criticizing KrylovKit or anything. I just wasn't able to figure out how to use it effectively to reach the results I wanted so far. Matt and I were and are still very interested to use it in ITensor, because we really like the idea of having a community standard for such algorithms that we can all rely on and improve.

So when I say the results weren't good, I just mean that when I called the eigsolve function within our DMRG code, I wasn't able to get our DMRG to converge. So for now I wrote a home-made Davidson code as a stand in so we could get the rest of our code tested.

Here is the way I was trying to call Lanczos (in an older commit):

```Julia
function iterEigSolve(PH,
                      phi::ITensor;
                      kwargs...)::Tuple{Number,ITensor}

  #
  # TODO: make version which takes krylovdim, maxiter
  #       was giving energies which randomly go up!
  #
  #tol = get(kwargs,:tol,10*eps(Float64))
  #krylovdim::Int = get(kwargs,:krylovdim,2)
  #maxiter::Int = get(kwargs,:maxiter,1)

  #actualdim = 1
  #for i in inds(phi)
  #  plev(i) == 0 && (actualdim *= dim(i))
  #end
  #if krylovdim > actualdim
  #  @printf "krylovdim=%d > actualdim=%d, resetting" krylovdim actualdim
  #  krylovdim = actualdim
  #end
  #lczos = Lanczos(tol=tol,krylovdim=krylovdim,maxiter=maxiter)
  #vals, vecs, info = eigsolve(PH,phi,1,:SR,lczos)

  vals, vecs, info = eigsolve(PH,phi,1,:SR,ishermitian=true)

  #@show info.normres[1]
  #@show info.numops
  #@show info.numiter
  return vals[1],vecs[1]
end
```

You can see from the commented and uncommented code that I was trying out different wants to use eigsolve, one with a Lanczos object plugged in and one without, and with different options, but I didn't get good energies.

Any comments you have would be appreciated!

**Comment by mtfishman** [comment]
Hey Miles,

At some point I had noticed that at least one of the overloads needed for KrylovKit (i.e. something like `axpy!`) was not defined correctly. This was early on, and I think around the time you had tried KrylovKit. Since then I think some of those functions have changed (and I am working on rounding out the in-place operation on ITensors now). We may want to try it again and get back to Jutho about this once we make sure we are not making a mistake on our end.

Cheers,
Matt

**Comment by emstoudenmire** [comment]
Thanks Matt. I didn't know that, but I can easily believe it given the early state the code was in at that time!

@Jutho: looking back over the documentation it does seem fairly comprehensive. It's hard to remember right now what I was missing. But one suggestion is it would be great to have a page of small examples of various typical use cases, such as Lanczos of a sparse Hermitian matrix to find the dominant eigenvector, etc. I see there are already some examples throughout the docs.

**Comment by Jutho** [comment]
I guess there are very few examples, writing tests and examples is not my best quality :-)

**Comment by Jutho** [comment]
I have no Davidson algorithm in KrylovKit.jl, and was under the impression that Davidson involes using the diagonal of the linear operator as a preconditioner. As this is not readily available if the linear operator is specified as a function, one would need to think about a nice/convenient API to pass along the diagonal, especially in more general cases where the vectors are not just plain vectors. 

Looking at your Davidson code in https://github.com/ITensor/ITensors.jl/blob/master/src/iterativesolvers.jl , however, I see no mention of the diagonal. Is this then not just the standard Lanczos algorithm that you have there?

**Comment by emstoudenmire** [comment]
Yes good point. It was based on some actual Davidson code but omits the diagonal step at the moment for some technical reasons. We may just leave out the diagonal step since I've found empirically that it often makes little difference. But then we should certainly rename the function so as not to be confusing! We'd be fine with using Lanczos if KrylovKit does not offer Davidson; perhaps it can also be added later so we can do some side-by-side comparisons.

**Comment by orialb** [comment]
I guess this can be closed for now. 

Just for future reference in case someone looks it up, I started working on the time evolution in https://github.com/orialb/TimeEvoMPS.jl . Currently TEBD (2nd order) seems to be working properly as far as I can tell.

Next step will be to add TDVP there, I will use KrylovKit for the exponentiation and could update in a separate issue how well it works.
